name: Checks

on:
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-clojure-deps
      - uses: jdx/mise-action@v2
        with:
          install_args: "babashka cljfmt clj-kondo java clojure"
      - name: Lint and format
        run: bb fmt-check bb deps && bb lint-init && bb lint

  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-clojure-deps
      - uses: jdx/mise-action@v2
        with:
          install_args: "babashka java clojure"
      - name: Outdated deps
        run: bb deps && bb outdated-check

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-clojure-deps
      - uses: jdx/mise-action@v2
        with:
          install_args: "babashka java clojure"
      - name: Run tests
        run: bb deps && bb test
